# FrontendLoader Guardfile

ignore_paths 'js.js','templates.js'

guard 'shell' do
  watch(/(.*).js/) {|m| `fel compile` } 
end

guard 'shell' do
  watch(/(.*).less/) {|m| `fel compile` }
end

guard 'shell' do
  watch(/(.*).mustache/) {|m| `fel compile` }
end
